In [2]:
import numpy as np 
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

In [3]:
reviews = [
    'nice food',
    'amazing restaurant',
    'too good',
    'just loved it!',
    'will go again',
    'horrible food',
    'never go there',
    'poor service',
    'poor quality',
    'needs improvement'
]

sentiments = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])




In [16]:
embbed = one_hot("amazing restaurant",30)
print(embbed)

[27, 8]


In [17]:
vocab_size = 30
# cara untuk mengencode sebuah kalimat atau phrase menjadi angka
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[19, 15], [27, 8], [10, 27], [11, 17, 20], [27, 24, 6], [6, 15], [17, 24, 26], [21, 23], [21, 5], [14, 20]]


In [19]:
max_length = 3
# membatasi panjang dari setiap kalimat
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[19 15  0]
 [27  8  0]
 [10 27  0]
 [11 17 20]
 [27 24  6]
 [ 6 15  0]
 [17 24 26]
 [21 23  0]
 [21  5  0]
 [14 20  0]]


In [24]:
embedded_vector_size = 4
model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name = "embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [21]:
x = padded_reviews
y = sentiments

In [25]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133 (532.00 Byte)
Trainable params: 133 (532.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
model.fit(x, y, epochs=50, verbose=0)

In [27]:
loss, accuracy = model.evaluate(x, y)
print('Accuracy: %f' % (accuracy*100))

1/1 [==============================] - 0s 156ms/step - loss: 0.6372 - accuracy: 1.0000
Accuracy: 100.000000


In [30]:
weight = model.get_layer('embedding').get_weights()[0]
len(weight)

30